/********************************************************************
* TIdentityDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TIdentityDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTIdentityDict();
extern void G__cpp_setup_inheritanceTIdentityDict();
extern void G__cpp_setup_typetableTIdentityDict();
extern void G__cpp_setup_memvarTIdentityDict();
extern void G__cpp_setup_globalTIdentityDict();
extern void G__cpp_setup_memfuncTIdentityDict();
extern void G__cpp_setup_funcTIdentityDict();
extern void G__set_cpp_environmentTIdentityDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TIdentity2D.h"
#include "TIdentityFunctions.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TIdentityDictLN_TClass;
extern G__linked_taginfo G__TIdentityDictLN_TBuffer;
extern G__linked_taginfo G__TIdentityDictLN_TMemberInspector;
extern G__linked_taginfo G__TIdentityDictLN_TObject;
extern G__linked_taginfo G__TIdentityDictLN_TNamed;
extern G__linked_taginfo G__TIdentityDictLN_TString;
extern G__linked_taginfo G__TIdentityDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TIdentityDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TIdentityDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentityDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TIdentityDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentityDictLN_TIdentityBase;
extern G__linked_taginfo G__TIdentityDictLN_TIdentityFunctions;
extern G__linked_taginfo G__TIdentityDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TIdentityDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TF1;
extern G__linked_taginfo G__TIdentityDictLN_TH1D;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TIdentityDictLN_TFile;
extern G__linked_taginfo G__TIdentityDictLN_TTree;
extern G__linked_taginfo G__TIdentityDictLN_TIdentity2D;

/* STUB derived class for protected member access */
